# Generated by Django 4.2.10 on 2025-06-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='emergency_contact_name',
            new_name='emergency_contact_first_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='comorbid_illnesses',
            field=models.JSONField(blank=True, help_text='List of comorbid illnesses', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='covid_vaccination_status',
            field=models.CharField(blank=True, choices=[('fully_vaccinated', 'Fully vaccinated'), ('partially_vaccinated', 'Partially vaccinated'), ('not_vaccinated', 'Not vaccinated')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_medical_history',
            field=models.JSONField(blank=True, help_text='List of family medical history', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital_admission_or_surgery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='maintenance_medications',
            field=models.JSONField(blank=True, help_text='List of maintenance medications', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Filipino', 'Filipino'), ('Foreigner', 'Foreigner'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_medical_history',
            field=models.JSONField(blank=True, help_text='List of past medical/surgical history', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='provincial_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='religion',
            field=models.CharField(blank=True, choices=[('Roman Catholic', 'Roman Catholic'), ('Seventh-day Adventist', 'Seventh-day Adventist'), ('Islam', 'Islam'), ('Protestant', 'Protestant'), ('Iglesia ni Cristo', 'Iglesia ni Cristo'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
