# Generated by Django 4.2.10 on 2025-06-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_appointment_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('has_toothbrush', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('dentition', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20, null=True)),
                ('periodontal', models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20, null=True)),
                ('occlusion', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Malocclusion', 'Malocclusion')], max_length=20, null=True)),
                ('malocclusion_severity', models.CharField(blank=True, choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('examined_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('permanent_teeth_status', models.JSONField(blank=True, help_text='Status of permanent teeth', null=True)),
                ('temporary_teeth_status', models.JSONField(blank=True, help_text='Status of temporary teeth', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dental_form_data', to='api.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_forms', to='api.patient')),
            ],
            options={
                'unique_together': {('patient', 'appointment')},
            },
        ),
    ]
