# Generated by Django 4.2.10 on 2025-06-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_medicaldocument_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='certificate_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='medical_certificates/'),
        ),
    ]
