# Generated by Django 4.2.10 on 2025-07-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_patient_barangay_patient_city_municipality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='provincial_address',
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
