# Generated by Django 4.2.10 on 2025-07-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_staffdetails_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='assigned_campuses',
            field=models.CharField(default='a', help_text='Comma-separated campus codes (a,b,c)', max_length=10),
        ),
    ]
