# Generated by Django 4.2.10 on 2025-07-04 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_staffdetails_assigned_campuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='blocked_reason',
            field=models.TextField(blank=True, help_text='Reason for blocking consultation access', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_consultation_blocked',
            field=models.BooleanField(default=False, help_text='If True, user cannot book consultations'),
        ),
    ]
