# Generated by Django 4.2.10 on 2025-07-06 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_add_academic_year_to_medicaldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='api.patient'),
        ),
    ]
