# Generated by Django 4.2.10 on 2025-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_medicaldocument_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital_admission_details',
            field=models.TextField(blank=True, help_text='Details of hospital admission or surgery when answer is Yes', null=True),
        ),
    ]
