# Generated by Django 4.2.10 on 2025-07-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_medicaldocument_advised_for_consultation_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalformdata',
            name='examiner_license',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='examiner_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='examiner_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='examiner_ptr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
