# Generated by Django 5.2.4 on 2025-07-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_patient_user_type_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymedicalhistoryitem',
            name='has_sub_options',
            field=models.BooleanField(default=False, help_text='Whether this item has sub-checkboxes'),
        ),
        migrations.AddField(
            model_name='familymedicalhistoryitem',
            name='requires_specification',
            field=models.BooleanField(default=False, help_text='Whether this item requires text specification'),
        ),
        migrations.AddField(
            model_name='familymedicalhistoryitem',
            name='specification_placeholder',
            field=models.CharField(blank=True, help_text='Placeholder text for specification field', max_length=200),
        ),
        migrations.AddField(
            model_name='familymedicalhistoryitem',
            name='sub_options',
            field=models.JSONField(blank=True, default=list, help_text='List of sub-option names'),
        ),
        migrations.AddField(
            model_name='pastmedicalhistoryitem',
            name='has_sub_options',
            field=models.BooleanField(default=False, help_text='Whether this item has sub-checkboxes'),
        ),
        migrations.AddField(
            model_name='pastmedicalhistoryitem',
            name='requires_specification',
            field=models.BooleanField(default=False, help_text='Whether this item requires text specification'),
        ),
        migrations.AddField(
            model_name='pastmedicalhistoryitem',
            name='specification_placeholder',
            field=models.CharField(blank=True, help_text='Placeholder text for specification field', max_length=200),
        ),
        migrations.AddField(
            model_name='pastmedicalhistoryitem',
            name='sub_options',
            field=models.JSONField(blank=True, default=list, help_text='List of sub-option names'),
        ),
    ]
