# Generated by Django 5.2.4 on 2025-07-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_familymedicalhistoryitem_has_sub_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital_admission_year',
            field=models.CharField(blank=True, help_text='Year of hospital admission or surgery', max_length=20, null=True),
        ),
    ]
