# Generated by Django 5.2.4 on 2025-07-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patient_hospital_admission_year'),
    ]

    operations = [
    ]
