# Generated by Django 4.2.10 on 2025-06-20 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_emergency_contact_name_patient_emergency_contact_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest_xray', models.FileField(blank=True, null=True, upload_to='medical_documents/chest_xray/')),
                ('cbc', models.FileField(blank=True, null=True, upload_to='medical_documents/cbc/')),
                ('blood_typing', models.FileField(blank=True, null=True, upload_to='medical_documents/blood_typing/')),
                ('urinalysis', models.FileField(blank=True, null=True, upload_to='medical_documents/urinalysis/')),
                ('drug_test', models.FileField(blank=True, null=True, upload_to='medical_documents/drug_test/')),
                ('hepa_b', models.FileField(blank=True, null=True, upload_to='medical_documents/hepa_b/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='waiver',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_waiver_per_user'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='api.patient'),
        ),
    ]
