# Generated by Django 5.2.4 on 2025-07-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20250722_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='menstrual_symptoms_other',
            field=models.TextField(blank=True, help_text='Specification for other menstrual symptoms', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='menstrual_symptoms',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
