# Generated by Django 4.2.10 on 2025-06-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_medicaldocument_waiver_unique_waiver_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='concern',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('medical', 'Medical'), ('dental', 'Dental')], default='medical', max_length=10),
        ),
    ]
