# Generated by Django 5.2.4 on 2025-07-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_patient_menstrual_symptoms_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comorbidillness',
            name='has_sub_options',
            field=models.BooleanField(default=False, help_text='Whether this illness has sub-options (checkboxes)'),
        ),
        migrations.AddField(
            model_name='comorbidillness',
            name='requires_specification',
            field=models.BooleanField(default=False, help_text='Whether this illness requires text specification'),
        ),
        migrations.AddField(
            model_name='comorbidillness',
            name='specification_placeholder',
            field=models.CharField(blank=True, help_text='Placeholder text for specification field', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comorbidillness',
            name='sub_options',
            field=models.JSONField(blank=True, help_text='List of sub-options for this illness', null=True),
        ),
    ]
