# Generated by Django 5.2.4 on 2025-07-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comorbidillness_has_sub_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='comorbid_illness_details',
            field=models.JSONField(blank=True, help_text='Enhanced comorbid illness sub-options and specifications', null=True),
        ),
    ]
