# Generated by Django 5.2.4 on 2025-07-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_comorbid_illness_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalinformationrecord',
            name='family_dentist_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalinformationrecord',
            name='family_dentist_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dentalinformationrecord',
            name='family_dentist_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dentalinformationrecord',
            name='has_family_dentist',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
