# Generated by Django 4.2.10 on 2025-06-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dentalformdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued')], default='pending', max_length=20),
        ),
    ]
