# Generated by Django 5.2.4 on 2025-07-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_family_dentist_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalinformationrecord',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentalinformationrecord',
            name='sex',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
