# Generated by Django 5.2.4 on 2025-07-22 06:29
# This migration acknowledges existing dental consultation fields that are already in the database

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_acknowledge_existing_dental_fields'),
    ]

    operations = [
        # These fields already exist in the database, we're just telling Django about them
        migrations.AddField(
            model_name='dentalformdata',
            name='consultation_template_compliant',
            field=models.BooleanField(default=True, help_text='Whether the consultation follows template'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='consultations_record',
            field=models.JSONField(blank=True, help_text='Record of all consultations', null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='current_bp',
            field=models.CharField(blank=True, help_text='Blood Pressure', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='current_consultation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='current_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='current_hr',
            field=models.CharField(blank=True, help_text='Heart Rate', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='current_management',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='current_nurse_physician',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='current_o2_sat',
            field=models.CharField(blank=True, help_text='Oxygen Saturation', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='current_rr',
            field=models.CharField(blank=True, help_text='Respiratory Rate', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='current_signs_symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='current_temp',
            field=models.CharField(blank=True, help_text='Temperature', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='current_test_results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='total_consultations',
            field=models.IntegerField(default=1, help_text='Total number of consultations'),
            preserve_default=False,
        ),
    ]
