# Generated by Django 4.2.10 on 2025-12-05 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_user_type_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalformdata',
            name='consultation_template_compliant',
            field=models.BooleanField(default=True, help_text='Whether the consultation follows template'),
        ),
        migrations.AlterField(
            model_name='dentalformdata',
            name='total_consultations',
            field=models.IntegerField(default=1, help_text='Total number of consultations'),
        ),
        migrations.CreateModel(
            name='ContentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_main_title', models.CharField(default='WMSU Health Services', max_length=200)),
                ('hero_sub_text', models.CharField(default='Your Health, Our Priority', max_length=200)),
                ('hero_description', models.TextField(default='Comprehensive healthcare services for the WMSU community')),
                ('hero_background_type', models.CharField(choices=[('maroon', 'Maroon'), ('image', 'Image')], default='image', max_length=20)),
                ('hero_background_image', models.URLField(blank=True, null=True)),
                ('announcements', models.JSONField(blank=True, default=list)),
                ('recent_activities', models.JSONField(blank=True, default=list)),
                ('services', models.JSONField(blank=True, default=list)),
                ('operating_hours_monday_friday', models.CharField(default='8:00 AM - 5:00 PM', max_length=100)),
                ('operating_hours_saturday', models.CharField(default='8:00 AM - 12:00 PM', max_length=100)),
                ('operating_hours_sunday', models.CharField(default='Closed (Emergency services available)', max_length=100)),
                ('contact_telephone', models.CharField(default='(062) 991-6736', max_length=50)),
                ('contact_email', models.EmailField(default='healthservices@wmsu.edu.ph', max_length=254)),
                ('contact_location', models.TextField(default='Health Services Building, WMSU Campus, Zamboanga City, Philippines')),
                ('cta_title', models.CharField(default='Ready to take charge of your health?', max_length=200)),
                ('cta_description', models.TextField(default='Sign up or log in to book appointments, access your medical records, view important health announcements, and streamline your healthcare journey with WMSU Health Services. Your well-being is our priority!')),
                ('logged_in_cta_title', models.CharField(default='Book your appointment now!', max_length=200)),
                ('logged_in_cta_description', models.TextField(default="Ready to prioritize your health? Click the button below to schedule your consultation, health check-up, or any other service you need. It's quick, easy, and ensures you get the care you deserve!")),
                ('post_login_options', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Management',
                'verbose_name_plural': 'Content Management',
            },
        ),
    ]
