# Generated by Django 4.2.10 on 2026-01-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_patient_nationality_specify'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='custom_drug_names',
            field=models.JSONField(blank=True, help_text='List of custom drug names specified by the user', null=True),
        ),
    ]
