# Generated by Django 4.2.10 on 2026-01-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_patient_custom_drug_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='custom_comorbid_illnesses',
            field=models.JSONField(blank=True, help_text='List of custom comorbid illnesses specified by the user', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='custom_menstrual_symptoms',
            field=models.JSONField(blank=True, help_text='List of custom menstrual symptoms specified by the user', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='custom_nationalities',
            field=models.JSONField(blank=True, help_text='List of custom nationalities specified by the user', null=True),
        ),
    ]
