# Generated by Django 4.2.10 on 2025-07-02 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_patient_provincial_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('main', 'Main Campus'), ('aurora', 'Aurora Campus'), ('pagadian', 'Pagadian Campus'), ('molave', 'Molave Campus')], max_length=20, unique=True)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('operating_days', models.JSONField(default=list, help_text='List of operating days')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['campus'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('validity_period_months', models.IntegerField(default=6, help_text='Document validity in months')),
                ('specific_courses', models.JSONField(default=list, help_text='List of courses that require this document')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('personal', 'Personal Information'), ('health', 'Health Information'), ('emergency', 'Emergency Contact'), ('family', 'Family History')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_requirements', models.JSONField(default=dict, help_text='Profile setup requirements configuration')),
                ('document_requirements', models.JSONField(default=dict, help_text='Medical document requirements configuration')),
                ('campus_schedules', models.JSONField(default=dict, help_text='Campus operating schedules')),
                ('dentist_schedules', models.JSONField(default=dict, help_text='Dentist availability schedules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.CreateModel(
            name='DentistSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentist_name', models.CharField(max_length=200)),
                ('campus', models.CharField(choices=[('main', 'Main Campus'), ('aurora', 'Aurora Campus'), ('pagadian', 'Pagadian Campus'), ('molave', 'Molave Campus')], max_length=20)),
                ('available_days', models.JSONField(default=list, help_text='List of available days')),
                ('time_slots', models.JSONField(default=list, help_text='List of available time slots')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['campus', 'dentist_name'],
                'unique_together': {('dentist_name', 'campus')},
            },
        ),
    ]
