# Generated by Django 4.2.10 on 2026-01-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_patient_custom_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='custom_comorbid_specifications',
            field=models.JSONField(blank=True, help_text='Object mapping illness names to their custom specifications (e.g., {"food_allergies": ["Peanuts", "Shrimp"]})', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='custom_comorbid_illnesses',
            field=models.JSONField(blank=True, help_text='List of custom comorbid illnesses specified by the user (for "Other Condition")', null=True),
        ),
    ]
