# Generated by Django 4.2.10 on 2026-01-10 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_custom_comorbid_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Announcement title', max_length=200)),
                ('message', models.TextField(help_text='Announcement message content')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the announcement', max_length=20)),
                ('icon', models.CharField(default='📢', help_text='Emoji or icon for the announcement', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this announcement is currently active')),
                ('show_on_login', models.BooleanField(default=True, help_text='Show this announcement to users upon login')),
                ('target_all_users', models.BooleanField(default=True, help_text='Show to all users')),
                ('target_user_types', models.JSONField(blank=True, default=list, help_text='List of user types to show this announcement to (e.g., ["student", "staff"])')),
                ('target_grade_levels', models.JSONField(blank=True, default=list, help_text='List of grade levels to show this announcement to (e.g., ["College", "Incoming Freshman"])')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for the announcement', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnnouncementView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='api.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'announcement')},
            },
        ),
    ]
