# Generated by Django 4.2.10 on 2025-07-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_campusschedule_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='campus',
            field=models.CharField(choices=[('a', 'Campus A'), ('b', 'Campus B'), ('c', 'Campus C')], default='a', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='campus_assigned',
            field=models.CharField(choices=[('a', 'Campus A'), ('b', 'Campus B'), ('c', 'Campus C')], default='a', max_length=20),
        ),
    ]
