# Generated by Django 4.2.10 on 2026-01-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_announcement_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicschoolyear',
            options={'ordering': ['-academic_year', '-semester_type']},
        ),
        migrations.AddField(
            model_name='academicschoolyear',
            name='semester_type',
            field=models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('Summer', 'Summer'), ('Full Year', 'Full Academic Year')], default='1st', help_text='Semester type', max_length=20),
        ),
    ]
