# Generated by Django 4.2.10 on 2026-01-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_semester_type_to_academic_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicschoolyear',
            unique_together={('academic_year', 'semester_type')},
        ),
        migrations.AddConstraint(
            model_name='academicschoolyear',
            constraint=models.UniqueConstraint(fields=('academic_year', 'semester_type'), name='unique_academic_year_semester'),
        ),
    ]
