# Generated by Django 4.2.10 on 2026-01-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_unique_constraint_academic_year_semester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['user', 'created_at'], name='api_patient_user_id_0a169f_idx'),
        ),
    ]
