# Generated by Django 4.2.10 on 2025-07-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_patient_student_id_alter_patient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
