# Generated by Django 4.2.10 on 2026-01-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_course_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='available_days',
            field=models.JSONField(blank=True, default=list, help_text='List of available days (e.g., ["Monday", "Tuesday"])'),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='blocked_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of blocked dates in YYYY-MM-DD format'),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='daily_appointment_limit',
            field=models.IntegerField(default=10, help_text='Maximum number of appointments per day'),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='time_slots',
            field=models.JSONField(blank=True, default=list, help_text='List of time slots (e.g., ["09:00-10:00", "13:00-14:00"])'),
        ),
    ]
