# Generated by Django 4.2.10 on 2026-01-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_staffdetails_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='religion_specify',
            field=models.CharField(blank=True, help_text='Specify religion if Other is selected', max_length=100, null=True),
        ),
    ]
