# Generated by Django 4.2.10 on 2025-07-04 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_customuser_blocked_at_customuser_blocked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blocked_reason',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_consultation_blocked',
        ),
        migrations.AddField(
            model_name='customuser',
            name='block_reason',
            field=models.TextField(blank=True, help_text='Reason for blocking the user', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Block user from booking consultations'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='blocked_at',
            field=models.DateTimeField(blank=True, help_text='When the user was blocked', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='blocked_by',
            field=models.ForeignKey(blank=True, help_text='Admin who blocked this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
