# Generated by Django 5.2.12 on 2026-05-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='religion',
            field=models.CharField(blank=True, choices=[('Roman Catholic', 'Roman Catholic'), ('Independent Catholic', 'Independent Catholic'), ('Aglipayan (Philippine Independent Church)', 'Aglipayan (Philippine Independent Church)'), ('Baptist', 'Baptist'), ('Methodist', 'Methodist'), ('Presbyterian', 'Presbyterian'), ('Lutheran', 'Lutheran'), ('Anglican/Episcopalian', 'Anglican/Episcopalian'), ('Evangelical', 'Evangelical'), ('Pentecostal', 'Pentecostal'), ('Born Again Christian', 'Born Again Christian'), ('United Church of Christ', 'United Church of Christ'), ('Church of Christ', 'Church of Christ'), ('Iglesia ni Cristo', 'Iglesia ni Cristo'), ('Iglesia Filipina Independiente', 'Iglesia Filipina Independiente'), ('Members Church of God International (MCGI)', 'Members Church of God International (MCGI)'), ('Seventh-day Adventist', 'Seventh-day Adventist'), ('Jesus is Lord Church', 'Jesus is Lord Church'), ('Jesus Miracle Crusade', 'Jesus Miracle Crusade'), ('Kingdom of Jesus Christ', 'Kingdom of Jesus Christ'), ('Philippine Benevolent Missionaries Association', 'Philippine Benevolent Missionaries Association'), ("Jehovah's Witnesses", "Jehovah's Witnesses"), ('Church of Jesus Christ of Latter-day Saints (Mormon)', 'Church of Jesus Christ of Latter-day Saints (Mormon)'), ('Islam - Sunni', 'Islam - Sunni'), ('Islam - Shia', 'Islam - Shia'), ('Islam', 'Islam (Other)'), ('Buddhism', 'Buddhism'), ('Hinduism', 'Hinduism'), ('Sikhism', 'Sikhism'), ('Judaism', 'Judaism'), ("Bahá'í Faith", "Bahá'í Faith"), ('Taoism', 'Taoism'), ('Confucianism', 'Confucianism'), ('Indigenous/Tribal Religion', 'Indigenous/Tribal Religion'), ('Atheist', 'Atheist'), ('Agnostic', 'Agnostic'), ('No Religion', 'No Religion'), ('Prefer not to say', 'Prefer not to say'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
