# Generated by Django 4.2.10 on 2025-07-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_patient_gender_alter_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='vaccination_history',
            field=models.JSONField(blank=True, help_text='Vaccination history with status for each vaccine', null=True),
        ),
    ]
