# Generated by Django 4.2.10 on 2025-07-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_patient_vaccination_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='covid_vaccination_status',
        ),
    ]
