# Generated by Django 5.2.4 on 2026-05-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalformdata',
            name='used_medicines',
            field=models.JSONField(blank=True, help_text='List of medicines used during the appointment', null=True),
        ),
    ]
