# Generated by Django 4.2.10 on 2025-07-05 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_patient_gender_alter_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_rescheduled',
            field=models.BooleanField(default=False, help_text='Whether this appointment has been rescheduled'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='original_date',
            field=models.DateField(blank=True, help_text='Original appointment date before reschedule', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='original_time',
            field=models.TimeField(blank=True, help_text='Original appointment time before reschedule', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_reason',
            field=models.TextField(blank=True, help_text='Reason for rescheduling', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, help_text='When the appointment was rescheduled', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_by',
            field=models.ForeignKey(blank=True, help_text='User who rescheduled this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
    ]
