# Generated by Django 4.2.10 on 2025-07-07 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_other_specification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='advised_for_consultation_at',
            field=models.DateTimeField(blank=True, help_text='When consultation was advised', null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='advised_for_consultation_by',
            field=models.ForeignKey(blank=True, help_text='Staff who advised for consultation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_advised_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='consultation_reason',
            field=models.TextField(blank=True, help_text='Reason for consultation advice', null=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('for_consultation', 'For Consultation'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('issued', 'Certificate Issued')], default='pending', max_length=20),
        ),
    ]
