# Generated by Django 4.2.10 on 2025-07-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_section_from_dental_info_record'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dentalwaiver',
            name='unique_dental_waiver_per_user_semester',
        ),
        migrations.RemoveField(
            model_name='dentalwaiver',
            name='school_year',
        ),
        migrations.AddConstraint(
            model_name='dentalwaiver',
            constraint=models.UniqueConstraint(fields=('user', 'semester'), name='unique_dental_waiver_per_user_semester'),
        ),
    ]
