# Generated by Django 4.2.10 on 2025-07-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_change_gender_to_sex_in_dental_info_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentalinformationrecord',
            old_name='gender',
            new_name='sex',
        ),
    ]
