# Generated by Django 4.2.10 on 2025-07-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_rename_gender_to_sex_dental_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalformdata',
            name='used_medicines',
            field=models.JSONField(blank=True, help_text='List of medicines used during the appointment', null=True),
        ),
    ]
