# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_dentalformdata_used_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalMedicineSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the medicine or supply', max_length=100)),
                ('type', models.CharField(choices=[('medicine', 'Medicine'), ('anesthetic', 'Anesthetic'), ('antibiotic', 'Antibiotic'), ('dental_supply', 'Dental Supply'), ('equipment', 'Equipment'), ('material', 'Material')], default='medicine', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description or notes about the item', null=True)),
                ('unit', models.CharField(default='pcs', help_text='Unit of measurement (e.g., mg, ml, pcs)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dental Medicine/Supply',
                'verbose_name_plural': 'Dental Medicines/Supplies',
                'ordering': ['type', 'name'],
            },
        ),
    ]
