# Generated by Django 4.2.10 on 2025-12-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_add_dental_medicine_supply_model'),
        ('api', '0057_populate_dental_medicines'),
    ]

    operations = [
    ]
