# Generated by Django 4.2.10 on 2025-07-16 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_a_empty_placeholder'),
        ('api', '0056_dentalmedicinesupply'),
        ('api', '0057_populate_dental_medicines'),
    ]

    operations = [
        # This is a merge migration to resolve parallel development branches
    ]
