# Generated by Django 4.2.10 on 2025-06-23 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_medicaldocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='submitted_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_document', to='api.patient'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('issued', 'Certificate Issued')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='medicaldocument',
            constraint=models.UniqueConstraint(fields=('patient',), name='unique_medical_document_per_patient'),
        ),
    ]
