# Generated by Django 4.2.10 on 2025-06-23 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_medicaldocument_certificate_issued_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='campus',
            field=models.CharField(choices=[('main', 'Main Campus'), ('aurora', 'Aurora Campus'), ('pagadian', 'Pagadian Campus'), ('molave', 'Molave Campus')], default='main', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='staff_signatures/')),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ptr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('campus_assigned', models.CharField(choices=[('main', 'Main Campus'), ('aurora', 'Aurora Campus'), ('pagadian', 'Pagadian Campus'), ('molave', 'Molave Campus')], default='main', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='staffdetails',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_staff_details_per_user'),
        ),
    ]
