# Generated by Django 4.2.10 on 2025-07-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_campusschedule_documentrequirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusschedule',
            name='campus',
            field=models.CharField(choices=[('a', 'Campus A'), ('b', 'Campus B'), ('c', 'Campus C')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='dentistschedule',
            name='campus',
            field=models.CharField(choices=[('a', 'Campus A'), ('b', 'Campus B'), ('c', 'Campus C')], max_length=20),
        ),
    ]
