# Generated by Django 4.2.10 on 2025-07-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_academicsemester_academicyear'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademicYear',
            new_name='AcademicSchoolYear',
        ),
        migrations.DeleteModel(
            name='AcademicSemester',
        ),
        migrations.AddField(
            model_name='appointment',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='api.academicschoolyear'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='api.academicschoolyear'),
        ),
        migrations.AddField(
            model_name='patient',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='api.academicschoolyear'),
        ),
        migrations.AlterModelTable(
            name='academicschoolyear',
            table='api_academicschoolyear',
        ),
    ]
