# Generated by Django 4.2.10 on 2025-07-04 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_academicyear_academicschoolyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('user', 'school_year')},
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['user', 'school_year'], name='api_patient_user_id_b1c93a_idx'),
        ),
    ]
