# Generated by Django 4.2.10 on 2025-07-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_covid_vaccination_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='student_id',
            field=models.CharField(default='TEMP-001', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vaccination_history',
            field=models.JSONField(blank=True, help_text='Vaccination history for all vaccines', null=True),
        ),
    ]
