# Generated by Django 4.2.10 on 2025-07-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_appointment_is_rescheduled_appointment_original_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalformdata',
            name='decayed_teeth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='filled_teeth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='missing_teeth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='next_appointment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='oral_hygiene',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='prevention_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='recommended_treatments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='treatment_priority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
