# Generated by Django 4.2.10 on 2025-07-05 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_add_dental_form_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicaldocument',
            name='unique_medical_document_per_patient',
        ),
        migrations.AddField(
            model_name='dentalformdata',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dental_forms', to='api.academicschoolyear'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='api.academicschoolyear'),
        ),
        migrations.AddField(
            model_name='medicalformdata',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_forms', to='api.academicschoolyear'),
        ),
        migrations.AddConstraint(
            model_name='medicaldocument',
            constraint=models.UniqueConstraint(fields=('patient', 'academic_year'), name='unique_medical_document_per_patient_year'),
        ),
    ]
