# Generated by Django 4.2.10 on 2025-07-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_update_dental_waiver_semester'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patient',
            name='api_patient_user_id_b1c93a_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='api_patient_user_id_5d3deb_idx',
            old_name='api_patient_user_school_semester_idx',
        ),
        migrations.RemoveField(
            model_name='dentalwaiver',
            name='parent_guardian_signature',
        ),
        migrations.AlterField(
            model_name='academicschoolyear',
            name='first_sem_end',
            field=models.DateField(blank=True, help_text='First semester end date', null=True),
        ),
        migrations.AlterField(
            model_name='academicschoolyear',
            name='first_sem_start',
            field=models.DateField(blank=True, help_text='First semester start date', null=True),
        ),
        migrations.AlterField(
            model_name='academicschoolyear',
            name='second_sem_end',
            field=models.DateField(blank=True, help_text='Second semester end date', null=True),
        ),
        migrations.AlterField(
            model_name='academicschoolyear',
            name='second_sem_start',
            field=models.DateField(blank=True, help_text='Second semester start date', null=True),
        ),
        migrations.AlterField(
            model_name='academicschoolyear',
            name='summer_end',
            field=models.DateField(blank=True, help_text='Summer semester end date', null=True),
        ),
        migrations.AlterField(
            model_name='academicschoolyear',
            name='summer_start',
            field=models.DateField(blank=True, help_text='Summer semester start date', null=True),
        ),
    ]
